server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: https

server:
  ssl:
    key-store: "classpath:localhost-ssl.p12"
    key-store-type: "PKCS12"
    key-alias: "localhost"
    enabled: true
    key-store-password: "s3cret"
  port: 8443




